# Generated by Django 4.2.11 on 2024-05-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ticket_price',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
