# Generated by Django 4.2.11 on 2024-05-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ticket_price',
            field=models.TextField(),
        ),
    ]
