# Generated by Django 4.2.11 on 2024-05-09 16:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_updated_on_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
