# Generated by Django 4.2.11 on 2024-04-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userspage',
            old_name='nickname',
            new_name='name',
        ),
    ]
