# Generated by Django 4.2.11 on 2024-04-27 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0002_rename_nickname_userspage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspage',
            name='image',
            field=models.ImageField(default='nobody.jpg', upload_to='user_pics'),
        ),
        migrations.AddField(
            model_name='userspage',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
