# Generated by Django 4.2.11 on 2024-04-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userspage_image_userspage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspage',
            name='date_created',
        ),
    ]
